Add missing definition and flag to semianalytic solver
to fix undefined reference to constructor, and allow for
solving only the inner two-scale iteration instead of the
full semianalytic iteration